[2023-12-07 16:25:43,281] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:25:43] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:25:43,284] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:25:43] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:25:43,819] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:25:43] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:42,848] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:48,126] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:48] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:48,326] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:48] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:48,867] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:48] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:48,881] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:48] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:48,884] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:48] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:50,293] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:50] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:50,354] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:50] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:50,387] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:50] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:50,440] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:50] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:26:51,242] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:26:51] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:18,471] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:26,062] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:26] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:26,678] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:26] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:27,339] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:27] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:27,351] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:27] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:27,360] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:27] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:29,078] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:29] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:29,117] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:29] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:29,183] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:29] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:29,187] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:29] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:27:29,816] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:27:29] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:54,628] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:56,463] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:56] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:56,860] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:56] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:57,214] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:57] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:57,245] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:57] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:57,327] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:57] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:58,277] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:58] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:58,319] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:58] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:58,389] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:58] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:58,393] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:58] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:28:58,940] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:28:58] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:29:20,813] ERROR log_exception() L1449 Exception on /avaliacao [POST] - call_trace=C:\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\mvp-qualidade-seguranca-sistemas-inteligentes\exemplo_mvp\api\app.py", line 74, in predict
    modelo = Model.carrega_modelo(ml_path)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Model' has no attribute 'carrega_modelo'
[2023-12-07 16:29:20,890] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:29:20] "[35m[1mPOST /avaliacao HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
